feat #15 : 가게 메뉴 등록 구현
f-lab-edu/Yummy-Delivery pull request #16
Opened 2021-12-26 07:59 UTC by log1995

2021-12-28 08:19 UTC, f-lab-joseph requested changes

2021-12-28 08:19 UTC, f-lab-joseph commented on src/main/java/com/yummy/delivery/controller/MenuController.java
> +    public void menuSet(@PathVariable("store_id") int store_id, Menu menu){
camel case 를 지켜주세요

2021-12-28 08:19 UTC, f-lab-joseph commented on src/main/java/com/yummy/delivery/domain/Menu.java
> +    private int id;
DTO, ENTITY 에서는 primitive type 대신 wrapper type 을 사용해주세요. 왜 그럴까요 ?

2021-12-28 08:19 UTC, f-lab-joseph commented on src/main/java/com/yummy/delivery/service/MenuService.java
> +    @Autowired
가능한 Autowired 대신 constructor injection 을 사용해주세요

2021-12-28 08:19 UTC, f-lab-joseph commented on src/main/java/com/yummy/delivery/service/MenuService.java
> +        menu.setCreated_at(LocalDateTime.now());
CAMEL CASE

2021-12-30 17:48 UTC, log1995 commented on src/main/java/com/yummy/delivery/domain/Menu.java
> +    private int id;
primitive type에는 null 값을 넣을 수 없기 때문에 DB 연동 시 해당 컬럼 값에 null이 필요할 경우 사용할 수가 없습니다.ㅔ

2022-01-09 02:37 UTC, f-lab-joseph approved these changes

2022-01-09 02:37 UTC, f-lab-joseph commented
머지하겠습니다.

2022-01-09 02:37 UTC, closed without merging