- API 수정
f-lab-edu/Yummy-Delivery pull request #19
Opened 2021-12-28 07:29 UTC by sproutboot

- 오타 수정

2021-12-28 08:20 UTC, f-lab-joseph commented
commit 의 이름을 의미있게 지어주세요.

https://www.google.com/search?q=commit+%EB%AA%85%EB%AA%85+%EA%B7%9C%EC%B9%99&newwindow=1&sxsrf=AOaemvInfXqzOX9t0tyNBBpq80chZBv-wg%3A1640679605550&ei=tcjKYdXyIOXk2roPqY6S-A8&ved=0ahUKEwiVodDoh4b1AhVlslYBHSmHBP8Q4dUDCA4&uact=5&oq=commit+%EB%AA%85%EB%AA%85+%EA%B7%9C%EC%B9%99&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgkIABCwAxAHEB46CAgAEIAEELADOgoIABCABBCHAhAUOgUIABCABDoECAAQHjoGCAAQBRAeOgUIABDNAjoGCCEQChAqSgQIQRgBSgQIRhgAUKADWMsYYIMZaAdwAHgBgAGHAYgBhBCSAQQwLjE3mAEAoAEByAEGwAEB&sclient=gws-wiz

2021-12-28 08:21 UTC, f-lab-joseph requested changes

2021-12-28 08:21 UTC, f-lab-joseph commented on src/main/java/com/yummy/delivery/domain/Seller.java
> +    private long id;
DTO, ENTITY 에서는 primitive type 대신 wrapper type 을 사용해주세요. 왜 그럴까요 ?

2021-12-28 08:21 UTC, f-lab-joseph commented on src/main/java/com/yummy/delivery/domain/User.java
> +    private long id;
DTO, ENTITY 에서는 primitive type 대신 wrapper type 을 사용해주세요. 왜 그럴까요 ?

2021-12-28 08:21 UTC, f-lab-joseph commented on src/main/java/com/yummy/delivery/domain/Seller.java
> +    private LocalDateTime updated_at;
camel case

2021-12-28 09:43 UTC, sproutboot commented on src/main/java/com/yummy/delivery/domain/Seller.java
> +    private long id;
primitive type을 사용하면 기본값이 0이기 때문에 실제로 id값이 0인지 null인지 구분하기가 어렵기 때문입니다.
하지만 wrapper type을 사용하면 id가 없는 경우에는 확실히 null을 확인할 수 있기 때문에 사용합니다.

2022-01-09 02:36 UTC, f-lab-joseph commented
@sproutboot 이 PR 은 조속히 수정해주시면 감사하겠습니다. 너무 오래 머지가 안되고 있네요

2022-01-13 12:46 UTC, merged